# Generated by Django 4.2.1 on 2023-06-03 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPL_API', '0002_alter_matches_umpire3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_data', to='IPL_API.matches'),
        ),
    ]
